:- prolog_load_context(directory, Dir),
   string_concat(Dir, '/code', Code),
   asserta(user:file_search_path(code, Code)),
   asserta(user:file_search_path(som, code('som'))),
   string_concat(Dir, '/../karma_prolog_utils/code', Utils),
   asserta(user:file_search_path(utils, Utils)),
   string_concat(Dir, '/../karma_actors/code', ActorS),
   asserta(user:file_search_path(actors, ActorS)),
   string_concat(Dir, '../karma_apperception/code', Apperception),
   asserta(user:file_search_path(apperception, Apperception)),
   string_concat(Dir, '/tests', Tests),
   asserta(user:file_search_path(tests, Tests)).
