:- prolog_load_context(directory, Dir),
   string_concat(Dir, '/../karma_prolog_utils/code', Utils),
   asserta(user:file_search_path(utils, Utils)),
   string_concat(Dir, '/../karma_actors/code', Actors),
   asserta(user:file_search_path(actors, Actors)),
   string_concat(Dir, '../karma_apperception/code', Apperception),
   asserta(user:file_search_path(apperception, Apperception)),
   string_concat(Dir, '/code', Code),
   asserta(user:file_search_path(agency, Code)),
   asserta(user:file_search_path(som, agency(som))),
   string_concat(Dir, '/tests', Tests),
   asserta(user:file_search_path(tests, Tests)).